### ISSUE TITLE
Create requirements.txt file

### ISSUE THREAD

**Issue by timothyb0912** [hassanobeid1994/tr_b_causal_2020#42]
- [ ] In my opinion, we should create a requirements.txt file to keep track of the dependencies for the project and ease the re-creation of the project's virtual environment.

At this point, all of us have written some code.

At minimum, we should ensure that the `requirements.txt` file contains all packages necessary to run all the notebooks in our `notebooks` folder and to import all the files in our `src` folder without error.

We should be able to point [Binder](https://mybinder.readthedocs.io/en/latest/) to our master branch and be able to run our code virtually.

**Comment by bouzaghrane** [comment]
@timothyb0912 I will create a new branch for this and add what I have so far. @hassanobeid1994 can follow and adjust based on what he has in his code/notebooks.

**Comment by bouzaghrane** [comment]
@timothyb0912 I have been trying to set up an empty virtual environment for the project to avoid any issues with any existing global packages and still be able to generate the `requirements.txt` file. 

However, when I create the environment using venv and launch jupyter lab from within the environment, it actually launches and all the packages work just fine. Do I need to create a separate kernel for the project as well? Any recommendations? Note I have anaconda installed, so that might be part of it?

**Comment by hassan-obeid** [comment]
@timothyb0912 @bouzaghrane I think this is (very) low priority. Please folks, no more organizational work before having something, and by something I mean:

Two datasets: one with independent variables as Xs, and one based on (any) causal graph. It is CRUCIAL to have this by end of this week.

**Comment by timothyb0912** [comment]
Closing since I have an environment.yml file for the repo.

However, it doesn't have all requirements. For instance, @hassanobeid1994 it doesn't have the tensorflow and related packages listed, so one wouldn't be able to run your public notebooks.

Cc @bouzaghrane for visibility.
