### ISSUE TITLE
Change of "realistic simulation" goals for week of Mar 8.

### ISSUE THREAD

**Issue by timothyb0912** [hassanobeid1994/tr_b_causal_2020#50]
@bouzaghrane and @hassanobeid1994 
I think that we must change our goals for Amine's "realistic simulation" work this week.

Currently, Amine is planning in #49  on extending his simulation to infer the functional forms for each node in a given causal graph, based on observed data.

I think this is unreasonable. That is equivalent to asking Amine to do MORE than perform a standard supervised learning task for each node in the graph. Note that a standard supervised learning task would just need to provide E[X_1 | X_2]. Now we need to provide all moments of the distribution in addition to the first.

I propose the following change of plans for Amine's work on the realistic simulation and to your work for the week, Hassan.

- [ ] 1. Hassan, you store the utility level causal graph in a standalone python file.
   A. Store the graph as an instance of a `causalgraphicalmodels.CausalGraphicalModel`. 
   B. Store the python file in a new directory, `src/registry`.
   C. Do all of this on a new branch and open a pull-request for the change.
   D. Tag Amine and I as reviewers!
- [ ] 2. Amine and Hassan, both of you take various nodes in the graph from the preceding step and try to fill in the best "distributional regressions"[^1] for it. Each of you should start with nodes on the path to different utilities.
- [ ] 3. Hassan, you should focus on powering through a single utility's entire path so you can simulate your dataset by Thursday. Amine, you can roam more freely through the nodes in the graph. Coordinate with Hassan to avoid duplicating work.

Let me know if you guys have any objections!

----------
[^1] Note distributional regression is really the term. Google scholar it! You guys will really just do the most lightweight version. Start with a regular regression then try getting better and better error terms. First fix variance, then fix shape, maybe? Or perhaps do the reverse? Whatever you do, just plan the pseudocode first and document that pseudocode in python comments, then write the code.

**Comment by timothyb0912** [comment]
@hassanobeid1994 and @bouzaghrane,
Can you two update your task lists (if necessary) to reflect these changes if you haven't already done so?

**Comment by hassan-obeid** [comment]
@timothyb0912 This all looks good to me, but I have some comments: 

- I can work specifically on coming up with a causal graph for the one utility I care about, run the distribution regressions (which if I understand correctly at this point, simply refers to regressing my confounded variables on the confounder). In my case, this will amount to regressing 3 or more variables on the travel distance (this may change based on the final causal graph I come up with). I can take care of that myself without involving amine, and have everything in one notebook. This will reduce overhead time due to communication/coordinating with Amine. 

- Amine can separately focus on working on his functions to eventually be able to simulate from a causal graph where we parametrically specify the relationship between nodes. In other words, his workflow won't need to worry about estimating those distributional regressions, and will take the output of those as input essentially. 

- The distributional regression estimation can be its separate workflow. Since I have to run some regressions this week anyway for my utility simulation work, this can be the building block for this workflow, and then we can generalize it/integrate it into Amine's. 

What do you all think? 

@bouzaghrane

**Comment by bouzaghrane** [comment]
@timothyb0912 @hassanobeid1994 All of this makes sense to me.  Let me update my task list accordingly.

**Comment by timothyb0912** [comment]
@hassanobeid1994 that all sounds good to me!

My one additional ask is if you can, please produce the entire utility-level causal graph, not just the graph for your utility.

My belief is that it really won't be much work given that you will have done it for one utility and given that you have the entire graph outside the nodes between X and Y. This ask is related to my previous comments [here](https://github.com/hassanobeid1994/tr_b_causal_2020/issues/12#issuecomment-592660168).

If I'm wrong and it's too much additional work or distracts from the tasks as they're already described, of course feel free to ignore this request!

**Comment by bouzaghrane** [comment]
@hassanobeid1994 @timothyb0912 check out [gamlss](https://www.gamlss.com/). The closest thing to it in Python is [PyGAM](https://github.com/dswah/pyGAM).

**Comment by timothyb0912** [comment]
@bouzaghrane word, I wish python had something similar!
