### ISSUE TITLE
Simulation and structure of the repo

### ISSUE THREAD

**Issue by bouzaghrane** [hassanobeid1994/tr_b_causal_2020#8]
Hey yall @timothyb0912 @hassanobeid1994,

As I said in the emails, I wanted to address a few things in this issue:

- In terms of notebook content: @timothyb0912 and @hassanobeid1994 please take a look at the notebook and let me know if the structure of the simulation makes sense. I just wanted us to have very minimal functional code before I organize it into classes/functions. I have a few issues with the numbers I get in there (mostly in terms of dominant alternatives), but it's nothing I didn't foresee. I don't think we should worry about the numbers for now and just get the reasoning of the simulation outlined.

- I am not sure if we should move the project organization notebooks somewhere else? (maybe to the docs folder) to keep the notebooks folder for actual analysis notebooks?  If we keep them in there, I think we should rename them to follow the naming convention we have in the cookie cutter structure. Any thoughts?

**Comment by timothyb0912** [comment]
@bouzaghrane I think it makes 100% sense to move the project organization notebooks elsewhere. How about the `references/` directory since that is supposed to be for "Data dictionaries, **manuals, and all other explanatory materials.**"

As for notebook structure. I will look now ( 👀) and comment back here.

**Comment by timothyb0912** [comment]
I mentioned this yesterday, but the structure looks good to me.

Refactor away into functions and classes, using the updated dataset.

Also, tag me on PRs for the refactoring early.

I'll likely have many comments on this. In general, try to keep one's notebook so that you simply call functions that are defined in one's src module. You can use the jupyter notebook autoreload magic (see description on cookiecutter data science site) to make it easy to edit the .py files and automatically have them available in the notebook.
